version: 2.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2015
environment:
  MADB_PFX_KEY:
    secure: FJBT+POuE4uUdLGJRsmNsw==
  VS_PFX_KEY:
    secure: LYUvBEhpB5ZzJT6ij5xnSQ4QoeasERP+iATMxhRqNhs=
  PUSHBULLET_API_TOKEN:
    secure: 2MwCYfQNYPfPjDqNJ1EL8VrIydQNRz3MfhnuI9dzSZag9JwCnqk5k3mMYTFn4ORk
	CI_PROJECT_FRIENDLY_NAME: Managed.Adb
install:
- ps: .\.appveyor\appveyor.install.ps1
before_build:
- ps: >-
    nuget.exe restore

    .\.appveyor\appveyor.before-build.ps1
build:
  project: .\.build\BuildAll.msbuild
  verbosity: detailed
after_build:
- ps: .\.appveyor\appveyor.after-build.ps1
artifacts:
- path: '**\Managed.Adb.*.zip'
  name: Zips
- path: '**\Managed.Adb.*.nupkg'
  name: Nupkg
before_deploy:
- ps: .\.appveyor\appveyor.before-deployment.ps1
deploy:
- provider: GitHub
  tag: $(APPVEYOR_PROJECT_NAME)-v$(CI_BUILD_VERSION)
  release: $(APPVEYOR_PROJECT_NAME)-v$(CI_BUILD_VERSION)
  description: $(CI_RELEASE_DESCRIPTION)
  auth_token:
    secure: UEgy2H9zJKLi599QoO3qVf5BKFqloRQ246ez9cEgsfV3vooAUfVopMS9+IjRtArL
  draft: true
  force_update: true
  on:
    branch: master
    CI_DEPLOY_GITHUB: True
- provider: NuGet
  api_key:
    secure: /M57OlSjcpugJFARA+j30alG5I+J1QxfRCDi5lWU3YhhzE1kxqLiAxtO+Bu7bQJt
  artifact: Nupkg
  on:
    branch: master
    CI_DEPLOY_NUGET: True
after_deploy:
- ps: .\.appveyor\appveyor.after-deployment.ps1
notifications:
- provider: Slack
  auth_token:
    secure: dEyWFeGEKdMmajrfGAYOGhWPEpivj1DiWu1xbbngPVcDW8vucg7JvWtJWTdARJ2bLedEg009P1o0JupLLx69Fg==
  channel: notifications
  on_build_success: true
  on_build_failure: true 
  on_build_status_changed: false 
